### ISSUE TITLE
参数优化报错

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy_spreadtrading#12]
engine.run_bf_optimization(opt_setting, output=True)

Traceback (most recent call last):
  File "C:\veighna_studio\lib\site-packages\vnpy\trader\optimize.py", line 114, in run_bf_optimization
    results: List[Tuple] = list(executor.map(evaluate_func, settings))
  File "C:\veighna_studio\lib\concurrent\futures\process.py", line 567, in _chain_from_iterable_of_lists
    for element in iterable:
  File "C:\veighna_studio\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "C:\veighna_studio\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\veighna_studio\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\veighna_studio\lib\multiprocessing\queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\veighna_studio\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle 'code' object

**Comment by noranhe** [comment]
请问用示例策略做优化也有同样的报错吗？
